export const FETCH_PORTFOLIO_DETAILS_START = 'FETCH_PORTFOLIO_DETAILS_START';
export const FETCH_PORTFOLIO_DETAILS_FAIL = 'FETCH_PORTFOLIO_DETAILS_FAIL';
export const FETCH_PORTFOLIO_DETAILS_SUCCESS = 'FETCH_PORTFOLIO_DETAILS_SUCCESS';
