export const FETCH_USER_INVESTMENT_SHARES_START = 'FETCH_USER_INVESTMENT_SHARES_START';
export const FETCH_USER_INVESTMENT_SHARES_FAIL = 'FETCH_USER_INVESTMENT_SHARES_FAIL';
export const FETCH_USER_INVESTMENT_SHARES_SUCCESS = 'FETCH_USER_INVESTMENT_SHARES_SUCCESS';