version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Generate mocked .env
          command: cp .env.template .env

      - run:
          name: Install Frontend Dependencies
          command: yarn install

      - run:
          name: Run eslint
          command: yarn lint

      - run:
          name: Run Jest
          command: yarn test

      - store_test_results:
          path: test-results

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
