export const FETCH_STOCK_DETAILS_START = 'FETCH_STOCK_DETAILS_START';
export const FETCH_STOCK_DETAILS_FAIL = 'FETCH_STOCK_DETAILS_FAIL';
export const FETCH_STOCK_DETAILS_SUCCESS = 'FETCH_STOCK_DETAILS_SUCCESS';
export const FETCH_HISTORY_CHART_DATA_START = 'FETCH_HISTORY_CHART_DATA_START';
export const FETCH_HISTORY_CHART_DATA_SUCCESS = 'FETCH_HISTORY_CHART_DATA_SUCCESS';
export const FETCH_HISTORY_CHART_DATA_FAIL = 'FETCH_HISTORY_CHART_DATA_FAIL';
