export const PURCHASE_STOCK_SUCCESS = 'PURCHASE_STOCK_SUCCESS';
export const PURCHASE_STOCK_FAIL = 'PURCHASE_STOCK_FAIL';
export const PURCHASE_STOCK_START = 'PURCHASE_STOCK_START';
export const PURCHASE_STOCK_RESET = 'PURCHASE_STOCK_RESET';
