export const FETCH_WATCHLIST_SUCCESS = 'FETCH_WATCHLIST_SUCCESS';
export const POST_WATCHLIST_SUCCESS = 'POST_WATCHLIST_SUCCESS';
export const DELETE_WATCHLIST = 'DELETE_WATCHLIST';
export const ADD_STOCK_TO_WATCHLIST = 'ADD_STOCK_TO_WATCHLIST';
export const REPLACE_WATCHLIST_STOCKS = 'DELETE_STOCK_IN_WATCHLIST';
