export const FETCH_INVESTED_STOCKS_START = 'FETCH_INVESTED_STOCKS_START';
export const FETCH_INVESTED_STOCKS_FAIL = 'FETCH_INVESTED_STOCKS_FAIL';
export const FETCH_INVESTED_STOCKS_SUCCESS = 'FETCH_INVESTED_STOCKS_SUCCESS';
